ALTER TABLE tb_usuario
    ALTER COLUMN id DROP DEFAULT;
ALTER TABLE tb_usuario
    ALTER COLUMN id TYPE VARCHAR(26);
ALTER TABLE tb_usuario
    ALTER COLUMN id SET NOT NULL;
DROP SEQUENCE IF EXISTS tb_usuario_id_seq;
